apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: spring-a

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-a
  labels:
    app: spring-a
    service: spring-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-a
      service: spring-a
  template:
    metadata:
      labels:
        app: spring-a
        service: spring-a
    spec:
      serviceAccountName: spring-a
      
      containers:
      - name: spring-a-container
        image: hhana982/spring-a:1.<version>
        ports:
        - containerPort: 8080
        
        env: 