apiVersion: v1
kind: Service
metadata:
  name: spring-a
  labels:
    app: spring-a
    service: spring-a
spec:
  selector:
    app: spring-a
    service: spring-a
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP